# Generated by Django 2.1.1 on 2018-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_almauser_user_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=30)),
                ('event_time', models.DateTimeField()),
                ('event_venue', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('event_poster', models.ImageField(blank=True, upload_to='event_posters')),
                ('event_going', models.IntegerField(default=0)),
            ],
        ),
    ]
