# Generated by Django 2.1.1 on 2018-10-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(choices=[('GENERAL', 'GEN'), ('EVENT', 'EVENT'), ('JOB OFFER', 'JOB')], max_length=10)),
                ('image_url', models.ImageField(blank=True, upload_to='')),
                ('post_desc', models.TextField(default='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AlmaUser')),
            ],
        ),
    ]
