# Generated by Django 2.1.1 on 2018-10-16 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
