# Generated by Django 2.1.1 on 2018-12-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_newsfeed_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cmnt_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmnt_text', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='feed_images'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.NewsFeed'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AlmaUser'),
        ),
    ]
