# Generated by Django 2.1.1 on 2018-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_jobsintern'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsintern',
            name='company_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='jobsintern',
            name='stipend',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
